// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0e6d645bd10e55ba "LaunchFolio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Footer' | 'Blog' // Variant
}} Props

 */
import {
	stdin_default,
	stdin_default2,
	stdin_default3,
} from "./chunks/chunk-ILSOYF5V.js";
import { Icon } from "./chunks/chunk-NI3BWCIH.js";
import { className, css, fonts } from "./chunks/chunk-3GSWMNFR.js";
import { routes } from "./chunks/chunk-UMI7NCHA.js";

// virtual:social-icons
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7HRe7iUVyrTgodZUEEWU/MgkzKnACaezwvxOEukJP/SiziyDfFp.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var XTwitterFonts = getFonts(stdin_default3);
var MotionAWithFX = withFX(motion.a);
var InstagramSocialFonts = getFonts(stdin_default);
var PhosphorFonts = getFonts(Icon);
var LinkedinSocialFonts = getFonts(stdin_default2);
var cycleOrder = ["FvxAV5TmU", "yyNhPl_Xo", "NMs8OtWR2"];
var serializationHash = "framer-wkVIX";
var variantClassNames = {
	FvxAV5TmU: "framer-v-182t2w2",
	NMs8OtWR2: "framer-v-en2sv5",
	yyNhPl_Xo: "framer-v-16mem1k",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 25,
	y: 0,
};
var transition2 = {
	delay: 0.4,
	duration: 0.6,
	ease: [0.4, 0, 0.2, 1],
	type: "tween",
};
var transition3 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	y: -5,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 5,
	y: 0,
};
var transition4 = {
	delay: 0.3,
	duration: 0.6,
	ease: [0.4, 0, 0.2, 1],
	type: "tween",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 15,
	y: 0,
};
var transition5 = {
	delay: 0.2,
	duration: 0.6,
	ease: [0.4, 0, 0.2, 1],
	type: "tween",
};
var animation4 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 10,
	y: 0,
};
var transition6 = {
	delay: 0.1,
	duration: 0.6,
	ease: [0.4, 0, 0.2, 1],
	type: "tween",
};
var animation5 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 20,
	y: 0,
};
var transition7 = {
	delay: 0,
	duration: 0.6,
	ease: [0.4, 0, 0.2, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Blog: "NMs8OtWR2",
	Default: "FvxAV5TmU",
	Footer: "yyNhPl_Xo",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "FvxAV5TmU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "FvxAV5TmU",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-182t2w2",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"FvxAV5TmU"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								NMs8OtWR2: {
									"data-framer-name": "Blog",
								},
								yyNhPl_Xo: {
									"data-framer-name": "Footer",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link
							href={"https://x.com/JosephAlexWeb"}
							motionChild={true}
							nodeId={"r_lm6Z43P"}
							openInNewTab={false}
							scopeId={"SiziyDfFp"}
						>
							<MotionAWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								aria-label={"X / Twitter Link"}
								className={"framer-18rl96e framer-dsijwc"}
								data-framer-name={"X - 0.4 delay"}
								layoutDependency={layoutDependency}
								layoutId={"r_lm6Z43P"}
								style={{
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(0, 0, 0, 0.5)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									WebkitBackdropFilter: "blur(10px)",
								}}
								variants={{
									NMs8OtWR2: {
										backgroundColor:
											"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
									},
									yyNhPl_Xo: {
										backgroundColor:
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
								}}
								whileHover={animation1}
							>
								{_jsx(stdin_default3, {
									animated: true,
									className: "framer-1s6o5f4",
									layoutDependency,
									layoutId: "BsQqKU82I",
									style: {
										"--1ww558a": 2,
										"--4rxgx6":
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
									variants: {
										yyNhPl_Xo: {
											"--4rxgx6":
												"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
										},
									},
								})}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ovh3pu"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"XImd4GQEa"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									variants={{
										yyNhPl_Xo: {
											"--extracted-r6o4lv":
												"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											yyNhPl_Xo: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-455vy9"}
															data-styles-preset={"xYEC_wF3E"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0)))",
															}}
														>
															{"1,214"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-455vy9"}
											data-styles-preset={"xYEC_wF3E"}
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255)))",
											}}
										>
											{"1,214"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</MotionAWithFX>
						</Link>
						<Link
							href={"https://www.instagram.com"}
							motionChild={true}
							nodeId={"yO47bIXS5"}
							openInNewTab={false}
							scopeId={"SiziyDfFp"}
						>
							<MotionAWithFX
								__framer__animate={{
									transition: transition4,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation2}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								aria-label={"Threads Link"}
								className={"framer-1454pdf framer-dsijwc"}
								data-framer-name={"Instagram - 0.3 delay"}
								layoutDependency={layoutDependency}
								layoutId={"yO47bIXS5"}
								style={{
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(0, 0, 0, 0.5)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									WebkitBackdropFilter: "blur(10px)",
								}}
								variants={{
									NMs8OtWR2: {
										backgroundColor:
											"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
									},
									yyNhPl_Xo: {
										backgroundColor:
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
								}}
								whileHover={animation1}
							>
								{_jsx(stdin_default, {
									animated: true,
									className: "framer-1mwd0sf",
									layoutDependency,
									layoutId: "xe7DccIRT",
									style: {
										"--1ww558a": 2,
										"--4rxgx6":
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
									variants: {
										yyNhPl_Xo: {
											"--4rxgx6":
												"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
										},
									},
								})}
							</MotionAWithFX>
						</Link>
						<Link
							href={"https://dribbble.com/"}
							motionChild={true}
							nodeId={"ESt5zDva8"}
							openInNewTab={false}
							scopeId={"SiziyDfFp"}
						>
							<MotionAWithFX
								__framer__animate={{
									transition: transition5,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								aria-label={"Dribbble Link"}
								className={"framer-1c5kx87 framer-dsijwc"}
								data-framer-name={"Dribble - 0.2 delay"}
								layoutDependency={layoutDependency}
								layoutId={"ESt5zDva8"}
								style={{
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(0, 0, 0, 0.5)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									WebkitBackdropFilter: "blur(10px)",
								}}
								variants={{
									NMs8OtWR2: {
										backgroundColor:
											"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
									},
									yyNhPl_Xo: {
										backgroundColor:
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
								}}
								whileHover={animation1}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1jbxiox-container"}
										data-framer-name={"Dribble Icon"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"CzbY8waPZ-container"}
										name={"Dribble Icon"}
										nodeId={"CzbY8waPZ"}
										rendersWithMotion={true}
										scopeId={"SiziyDfFp"}
									>
										<Icon
											color={
												"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"DribbbleLogo"}
											id={"CzbY8waPZ"}
											layoutId={"CzbY8waPZ"}
											mirrored={false}
											name={"Dribble Icon"}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													yyNhPl_Xo: {
														color:
															"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</MotionAWithFX>
						</Link>
						<Link
							href={"https://www.behance.net/"}
							motionChild={true}
							nodeId={"DD1TGNJGO"}
							openInNewTab={false}
							scopeId={"SiziyDfFp"}
						>
							<MotionAWithFX
								__framer__animate={{
									transition: transition6,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation4}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								aria-label={"Behance Link"}
								className={"framer-1bwrckd framer-dsijwc"}
								data-framer-name={"Behance - 0.1 delay"}
								layoutDependency={layoutDependency}
								layoutId={"DD1TGNJGO"}
								style={{
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(0, 0, 0, 0.5)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									WebkitBackdropFilter: "blur(10px)",
								}}
								variants={{
									NMs8OtWR2: {
										backgroundColor:
											"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
									},
									yyNhPl_Xo: {
										backgroundColor:
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
								}}
								whileHover={animation1}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1dpbkj-container"}
										data-framer-name={"Behance Logo"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"FzveQLByO-container"}
										name={"Behance Logo"}
										nodeId={"FzveQLByO"}
										rendersWithMotion={true}
										scopeId={"SiziyDfFp"}
									>
										<Icon
											color={
												"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"BehanceLogo"}
											id={"FzveQLByO"}
											layoutId={"FzveQLByO"}
											mirrored={false}
											name={"Behance Logo"}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													yyNhPl_Xo: {
														color:
															"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</MotionAWithFX>
						</Link>
						<Link
							href={"https://www.linkedin.com/"}
							motionChild={true}
							nodeId={"wgs4fW3qp"}
							openInNewTab={false}
							scopeId={"SiziyDfFp"}
						>
							<MotionAWithFX
								__framer__animate={{
									transition: transition7,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation5}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								aria-label={"Linkedin Link"}
								className={"framer-nnayh3 framer-dsijwc"}
								data-framer-name={"LinkedIn - 0 delay"}
								layoutDependency={layoutDependency}
								layoutId={"wgs4fW3qp"}
								style={{
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(0, 0, 0, 0.5)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									WebkitBackdropFilter: "blur(10px)",
								}}
								variants={{
									NMs8OtWR2: {
										backgroundColor:
											"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
									},
									yyNhPl_Xo: {
										backgroundColor:
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
								}}
								whileHover={animation1}
							>
								{_jsx(stdin_default2, {
									animated: true,
									className: "framer-n31vj8",
									layoutDependency,
									layoutId: "wCvDTkOHM",
									style: {
										"--1ww558a": 2,
										"--4rxgx6":
											"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
									},
									variants: {
										yyNhPl_Xo: {
											"--4rxgx6":
												"var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
										},
									},
								})}
							</MotionAWithFX>
						</Link>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wkVIX.framer-dsijwc, .framer-wkVIX .framer-dsijwc { display: block; }",
	".framer-wkVIX.framer-182t2w2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-wkVIX .framer-18rl96e, .framer-wkVIX .framer-1454pdf, .framer-wkVIX .framer-1c5kx87, .framer-wkVIX .framer-1bwrckd, .framer-wkVIX .framer-nnayh3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-wkVIX .framer-1s6o5f4 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 14px); position: relative; width: 14px; }",
	".framer-wkVIX .framer-1ovh3pu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-wkVIX .framer-1mwd0sf, .framer-wkVIX .framer-n31vj8 { flex: none; height: var(--framer-aspect-ratio-supported, 14px); position: relative; width: 14px; }",
	".framer-wkVIX .framer-1jbxiox-container, .framer-wkVIX .framer-1dpbkj-container { flex: none; height: 14px; position: relative; width: 14px; }",
	...css,
];
var FramerSiziyDfFp = withCSS(Component, css2, "framer-wkVIX");
var stdin_default4 = FramerSiziyDfFp;
FramerSiziyDfFp.displayName = "Social Icons";
FramerSiziyDfFp.defaultProps = {
	height: 30,
	width: 208,
};
addPropertyControls(FramerSiziyDfFp, {
	variant: {
		options: ["FvxAV5TmU", "yyNhPl_Xo", "NMs8OtWR2"],
		optionTitles: ["Default", "Footer", "Blog"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerSiziyDfFp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...XTwitterFonts,
		...InstagramSocialFonts,
		...PhosphorFonts,
		...LinkedinSocialFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:social-icons
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "FvxAV5TmU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0e6d645bd10e55baeaf5506a44fad69a4a32a264fb6901dc89344048fda9ac90"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SocialIconsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0e6d645bd10e55baeaf5506a44fad69a4a32a264fb6901dc89344048fda9ac90"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var social_icons_default = ComponentWithRoot;
export { social_icons_default as default };
