// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 0e6d645bd10e55ba "LaunchFolio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * company?: string // Company
 * date?: string // Date
 * title?: string // Title
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-3GSWMNFR.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-B53WOYBJ.js";
import { routes } from "./chunks/chunk-UMI7NCHA.js";

// virtual:work-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/hIMP4OLMQzj11nPy6CZL/aiYsCZwmd1paQtU0lail/VaHmJ_0mu.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-1qiCu";
var variantClassNames = {
	mWXUroCXi: "framer-v-1v7iyva",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ company, date, height, id, title, width, ...props }) => {
	return {
		...props,
		MtwQdXmPu: date ?? props.MtwQdXmPu ?? "2020-2022",
		Q9Y3Wh1N0: title ?? props.Q9Y3Wh1N0 ?? "Staff Product Designer",
		u951OiT8B: company ?? props.u951OiT8B ?? "ZigZag",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		u951OiT8B: u951OiT8B2,
		MtwQdXmPu: MtwQdXmPu2,
		Q9Y3Wh1N0: Q9Y3Wh1N02,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "mWXUroCXi",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1v7iyva",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"History"}
						layoutDependency={layoutDependency}
						layoutId={"mWXUroCXi"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-e3a90888-763b-420f-bb27-f2520e07d9b1, rgb(222, 222, 222))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, rgb(255, 255, 255))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow:
								"0px 0.5971439051427296px 0.5971439051427296px -0.9375px rgba(0, 0, 0, 0.07), 0px 1.8108796073283884px 1.8108796073283884px -1.875px rgba(0, 0, 0, 0.07), 0px 4.786990141113346px 4.786990141113346px -2.8125px rgba(0, 0, 0, 0.06), 0px 15px 15px -3.75px rgba(0, 0, 0, 0.03)",
							...style,
						}}
					>
						<motion.div
							className={"framer-ctsyc2"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"DnmWMRMtH"}
						>
							<motion.div
								className={"framer-a9yo0v"}
								data-framer-name={"Company & Dates"}
								layoutDependency={layoutDependency}
								layoutId={"NkmUCy2GZ"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1wjplei"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Fmi5iEI9i"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={u951OiT8B2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1pvr9s"}
											data-styles-preset={"aPqv2C1EJ"}
											dir={"auto"}
										>
											{"ZigZag"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-uvrv9v"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"pwvhmRABd"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Q9Y3Wh1N02}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-455vy9"}
											data-styles-preset={"xYEC_wF3E"}
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84)))",
											}}
										>
											{"Staff Product Designer"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-6bebwn"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"xFlTvv3NA"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={MtwQdXmPu2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-455vy9"}
										data-styles-preset={"xYEC_wF3E"}
										dir={"auto"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-994646e0-68ea-49d7-897a-104048558f6f, rgb(84, 84, 84)))",
										}}
									>
										{"2020-2022"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-1qiCu.framer-fkch29, .framer-1qiCu .framer-fkch29 { display: block; }",
	".framer-1qiCu.framer-1v7iyva { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 18px; position: relative; width: 300px; }",
	".framer-1qiCu .framer-ctsyc2 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-1qiCu .framer-a9yo0v { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-1qiCu .framer-1wjplei { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }",
	".framer-1qiCu .framer-uvrv9v, .framer-1qiCu .framer-6bebwn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css2,
	...css,
	'.framer-1qiCu[data-border="true"]::after, .framer-1qiCu [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerVaHmJ_0mu = withCSS(Component, css3, "framer-1qiCu");
var stdin_default = FramerVaHmJ_0mu;
FramerVaHmJ_0mu.displayName = "Work Card";
FramerVaHmJ_0mu.defaultProps = {
	height: 76,
	width: 300,
};
addPropertyControls(FramerVaHmJ_0mu, {
	u951OiT8B: {
		defaultValue: "ZigZag",
		displayTextArea: false,
		title: "Company",
		type: ControlType.String,
	},
	MtwQdXmPu: {
		defaultValue: "2020-2022",
		displayTextArea: false,
		title: "Date",
		type: ControlType.String,
	},
	Q9Y3Wh1N0: {
		defaultValue: "Staff Product Designer",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerVaHmJ_0mu,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:work-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0e6d645bd10e55baeaf5506a44fad69a4a32a264fb6901dc89344048fda9ac90"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WorkCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"0e6d645bd10e55baeaf5506a44fad69a4a32a264fb6901dc89344048fda9ac90"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var work_card_default = ComponentWithRoot;
export { work_card_default as default };
